### PR TITLE
Fix access to variable before assignment (admin/fetch point of sales)

### PR DESCRIPTION
**Pull request by lardissone**
Quick fix that corrects an issue when trying to fetch point of sales from the admin.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
What's the error you're seeing? None of the lines you're indenting should raise an error.

**Comment by lardissone** [comment]
@WhyNotHugo can't replicate since I'm gated with a 602 error now, but it was crashing on `created = len([pos for pos in poses if pos[1]])` saying that `poses` was not defined.

**Comment by lardissone** [comment]
Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1964, in changelist_view
    response = self.response_action(
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1593, in response_action
    response = func(self, request, queryset)
  File "/Users/lardissone/Library/Caches/pypoetry/virtualenvs/afip-MV8H6OUK-py3.10/lib/python3.10/site-packages/django_afip/admin.py", line 290, in fetch_points_of_sales
    created = len([pos for pos in poses if pos[1]])
UnboundLocalError: local variable 'poses' referenced before assignment
```

**Comment by WhyNotHugo** [comment]
Ah, right, if an error was raised, then that variable is never assigned. `catch_exceptions` is terrible.

**Comment by WhyNotHugo** [comment]
Thanks!

**Pull request merged**
